id: I2D947611
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T01:01:44.205059'
last_modified: '2022-06-19T01:01:44.205076'
parser: null
source_metadata:
  title: Eulogy in praise of Gong dkar Kun dga rnam rgyal (1432-1496), colophon excerpt
  author: mkhan chen nam mkha chos bzang /
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2014-11-06); unrevised, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/934
  bases:
    d613:
      title: Eulogy in praise of Gong dkar Kun dga rnam rgyal (1432-1496), colophon
        excerpt
      order: 1
      base_file: d613.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
